"""init

Revision ID: 6dee24e1af93
Revises: 
Create Date: 2024-03-23 17:53:15.101938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6dee24e1af93"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("registration_name", sa.String(), nullable=False),
        sa.Column("is_bot_admin", sa.Boolean(), nullable=False),
        sa.Column("is_reg_admin", sa.Boolean(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=True),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("connected_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "lessons_instructors",
        sa.Column("object_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("updated_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("object_id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("object_id"),
    )
    op.create_table(
        "lessons_places",
        sa.Column("object_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("updated_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("object_id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("object_id"),
    )
    op.create_table(
        "lessons_types",
        sa.Column("object_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("updated_user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["updated_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("object_id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("object_id"),
    )
    op.create_table(
        "user_lesson_registration_process",
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("object_id"),
    )
    op.create_table(
        "user_lesson_registrations",
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("date", sa.String(), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("place", sa.String(), nullable=False),
        sa.Column("need_theory", sa.Boolean(), nullable=False),
        sa.Column("start_time", sa.String(), nullable=False),
        sa.Column("instructor", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("object_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_lesson_registrations")
    op.drop_table("user_lesson_registration_process")
    op.drop_table("lessons_types")
    op.drop_table("lessons_places")
    op.drop_table("lessons_instructors")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
