"""add user chat_id

Revision ID: 80115fdd1896
Revises: 33c93a9a1189
Create Date: 2024-03-11 20:54:56.641921

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "80115fdd1896"
down_revision: Union[str, None] = "33c93a9a1189"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("chat_id", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "chat_id")
    # ### end Alembic commands ###
