"""users

Revision ID: 33c93a9a1189
Revises: 
Create Date: 2024-03-10 21:47:30.296804

"""

from datetime import datetime, UTC
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.db import Users

# revision identifiers, used by Alembic.
revision: str = "33c93a9a1189"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("registration_name", sa.String(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.String(), nullable=False),
        sa.Column("connected_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "user_lesson_registration_process",
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("chat_id", sa.String(), nullable=False),
        sa.Column("message_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("object_id"),
    )

    from sqlalchemy import orm

    user = Users(
        id=780902707,
        username="lemtse_vitaliy",
        first_name="Виталий",
        last_name="Лемцё",
        registration_name="Виталий Л",
        updated_at=str(datetime.now(UTC)),
        is_admin=True,
    )

    bind = op.get_bind()
    session = orm.Session(bind=bind)
    session.add(user)
    session.commit()
    session.close()

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_lesson_registration_process")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
